name: My Snyk Demo AWS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: mvn build and run
      run: |
        mvn install
        cd ./todolist-web-struts && mvn tomcat7:run 
  scan_vuln:
    runs-on: snyk/snyk:maven

    steps:
    - uses: actions/checkout@v3
    - name: Snyk Scan Application files
      run: |
        mvn install 
        echo ''
        echo '' && echo 'Snyk Code' && echo ''
        snyk code test --org=demo_high  || true
        echo ''
        echo '' && echo 'Snyk OpenSource' && echo ''
        snyk test --org=demo_high --all-projects || true
        echo ''
        echo '' && echo 'Snyk IaC' && echo ''
        snyk iac test --org=demo_high || true
        echo ''
        snyk monitor --org=demo_high --all-projects --remote-repo-url=aws-snyk-mvn-goof
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my-snyk-demo-mvn-goof:$(date +%s)
        docker run --rm -it --env SNYK_TOKEN -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk:docker snyk container test --print-deps --org=demo_high --project-name=my-snyk-demo-mvn-goof --app-vulns --nested-jars-depth=8 my-snyk-demo-mvn-goof:$(date +%s) || true
        docker run --rm -it --env SNYK_TOKEN -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk:docker snyk container monitor --print-deps --org=demo_high --file=Dockerfile --project-name=my-snyk-demo-mvn-goof --app-vulns --nested-jars-depth=8 my-snyk-demo-mvn-goof:$(date +%s) || true
        docker push --tag my-snyk-demo-mvn-goof:$(date +%s)

