name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag my-snyk-demo-mvn-goof:$(date +%s)
    - name: Vulnerability scan with Snyk Container
      run: |
        DOCKER_LOGIN=${{ secrets.DOCKER_LOGI }}
        SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}
        docker run --env $SNYK_TOKEN -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk:docker snyk container test --print-deps --org=demo_high --project-name=${{github.repository}} --app-vulns --nested-jars-depth=8 $DOCKER_LOGIN/my-snyk-demo-mvn-goof:$(date +%s) 
