name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
steps:
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag my-snyk-demo-mvn-goof:$(date +%s)
    - name: Vulnerability scan with Snyk Container
      with: # Set the secret as an input
        snyk_token: ${{ secrets.SNYK_TOKEN }}
      env: # Or as an environment variable
        snyk_toekn: ${{ secrets.SNYK_TOKEN }}
    - uses: actions/checkout@v1
      run: |
        docker run --env $snyk_token -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk:docker snyk auth ${{ secrets.SNYK_TOKEN }} && snyk container test --print-deps --org=demo_high --project-name=${{github.repository}} --app-vulns --nested-jars-depth=8 DOCKER_LOGIN/my-snyk-demo-mvn-goof:$(date +%s) 
