name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag my-snyk-demo-mvn-goof:$(date +%s)
    - name: Vulnerability scan with Snyk Container
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "set api key for ${{env.DOCKER_LOGIN}}"
        docker run -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk:docker snyk config set api=${{env.SNYK_TOKEN}}
        echo "execute snyk auth for ${{env.DOCKER_LOGIN}}"
        docker run -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk:docker snyk auth ${{env.SNYK_TOKEN}}
        echo "execute docker run for ${{env.DOCKER_LOGIN}}"
        docker run -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk:docker snyk container test --print-deps --org=demo_high --project-name=${{github.repository}} --app-vulns --nested-jars-depth=8 lucmaeda/my-snyk-demo-mvn-goof:$(date +%s)
